import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/lib/auth";
import { SessionNavbar } from "@/components/auth/session-navbar";
import { Toaster as SoonnerToaster } from "@/components/ui/sonner"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function ProtectedLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await auth();
    return (
        <SessionProvider session={session}>
             <SoonnerToaster/>
            <SessionNavbar/>
            <div >
                {children}
            </div>
        </SessionProvider>
    );
}
